export interface GroceryCategory {
  id: string
  name: string
  emoji: string
  color: string
}

export const GROCERY_CATEGORIES: GroceryCategory[] = [
  { id: 'produce', name: 'Fruits & Légumes', emoji: '🥦', color: 'text-emerald-600 bg-emerald-50' },
  { id: 'dairy', name: 'Frais & Crèmerie', emoji: '🧀', color: 'text-amber-600 bg-amber-50' },
  { id: 'bakery', name: 'Boulangerie', emoji: '🥖', color: 'text-orange-600 bg-orange-50' },
  { id: 'meat', name: 'Boucherie & Poisson', emoji: '🥩', color: 'text-rose-600 bg-rose-50' },
  { id: 'pantry', name: 'Épicerie & Féculents', emoji: '🥫', color: 'text-yellow-600 bg-yellow-50' },
  { id: 'drinks', name: 'Boissons', emoji: '🧃', color: 'text-blue-600 bg-blue-50' },
  { id: 'frozen', name: 'Surgelés', emoji: '🧊', color: 'text-cyan-600 bg-cyan-50' },
  { id: 'home', name: 'Maison & Hygiène', emoji: '🧼', color: 'text-purple-600 bg-purple-50' },
  { id: 'other', name: 'Divers', emoji: '📦', color: 'text-slate-600 bg-slate-50' },
]

// Dictionnaire intelligent de classification Bring!
const KEYWORDS_TO_CATEGORY: Record<string, string> = {
  // Fruits & Légumes
  'pomme': 'produce',
  'pommes': 'produce',
  'banane': 'produce',
  'bananes': 'produce',
  'poire': 'produce',
  'poires': 'produce',
  'orange': 'produce',
  'oranges': 'produce',
  'citron': 'produce',
  'citrons': 'produce',
  'fraise': 'produce',
  'fraises': 'produce',
  'framboise': 'produce',
  'framboises': 'produce',
  'raisin': 'produce',
  'raisins': 'produce',
  'avocat': 'produce',
  'avocats': 'produce',
  'tomate': 'produce',
  'tomates': 'produce',
  'salade': 'produce',
  'concombre': 'produce',
  'concombres': 'produce',
  'carotte': 'produce',
  'carottes': 'produce',
  'oignon': 'produce',
  'oignons': 'produce',
  'ail': 'produce',
  'échalote': 'produce',
  'echalote': 'produce',
  'poivron': 'produce',
  'poivrons': 'produce',
  'courgette': 'produce',
  'courgettes': 'produce',
  'aubergine': 'produce',
  'aubergines': 'produce',
  'pomme de terre': 'produce',
  'pommes de terre': 'produce',
  'patate': 'produce',
  'patates': 'produce',
  'champignon': 'produce',
  'champignons': 'produce',
  'épinard': 'produce',
  'epinard': 'produce',
  'épinards': 'produce',
  'brocoli': 'produce',
  'chou': 'produce',
  'haricot': 'produce',
  'haricots': 'produce',
  'poireau': 'produce',
  'poireaux': 'produce',
  'radis': 'produce',
  'mangue': 'produce',
  'ananas': 'produce',
  'kiwi': 'produce',
  'pasteque': 'produce',
  'pastèque': 'produce',
  'melon': 'produce',
  'persil': 'produce',
  'coriandre': 'produce',
  'basilic': 'produce',
  'menthe': 'produce',

  // Frais & Crèmerie
  'lait': 'dairy',
  'yaourt': 'dairy',
  'yaourts': 'dairy',
  'fromage': 'dairy',
  'fromages': 'dairy',
  'beurre': 'dairy',
  'creme': 'dairy',
  'crème': 'dairy',
  'oeuf': 'dairy',
  'oeufs': 'dairy',
  'œuf': 'dairy',
  'œufs': 'dairy',
  'parmesan': 'dairy',
  'gruyere': 'dairy',
  'gruyère': 'dairy',
  'emmental': 'dairy',
  'comte': 'dairy',
  'comté': 'dairy',
  'mozzarella': 'dairy',
  'chevre': 'dairy',
  'chèvre': 'dairy',
  'feta': 'dairy',
  'ricotta': 'dairy',
  'mascarpone': 'dairy',
  'gouda': 'dairy',
  'cheddar': 'dairy',
  'roquefort': 'dairy',
  'brie': 'dairy',
  'camembert': 'dairy',
  'râpé': 'dairy',
  'rape': 'dairy',

  // Boulangerie
  'pain': 'bakery',
  'baguette': 'bakery',
  'baguettes': 'bakery',
  'brioche': 'bakery',
  'croissant': 'bakery',
  'croissants': 'bakery',
  'pain au chocolat': 'bakery',
  'chocolatine': 'bakery',
  'pain de mie': 'bakery',
  'biscottes': 'bakery',
  'crepe': 'bakery',
  'crêpe': 'bakery',
  'crêpes': 'bakery',
  'pancake': 'bakery',
  'pancakes': 'bakery',
  'tortilla': 'bakery',
  'tortillas': 'bakery',
  'pita': 'bakery',
  'burger bun': 'bakery',
  'buns': 'bakery',

  // Boucherie & Poisson
  'viande': 'meat',
  'poulet': 'meat',
  'boeuf': 'meat',
  'bœuf': 'meat',
  'porc': 'meat',
  'veau': 'meat',
  'steak': 'meat',
  'steaks': 'meat',
  'hache': 'meat',
  'haché': 'meat',
  'jambon': 'meat',
  'lardon': 'meat',
  'lardons': 'meat',
  'saucisse': 'meat',
  'saucisses': 'meat',
  'saucisson': 'meat',
  'merguez': 'meat',
  'chipolata': 'meat',
  'poisson': 'meat',
  'saumon': 'meat',
  'thon': 'meat',
  'cabillaud': 'meat',
  'crevette': 'meat',
  'crevettes': 'meat',
  'colin': 'meat',
  'dinde': 'meat',
  'bacon': 'meat',
  'chorizo': 'meat',

  // Épicerie & Féculents
  'pate': 'pantry',
  'pates': 'pantry',
  'pâte': 'pantry',
  'pâtes': 'pantry',
  'spaghetti': 'pantry',
  'penne': 'pantry',
  'coquillette': 'pantry',
  'coquillettes': 'pantry',
  'tagliatelle': 'pantry',
  'riz': 'pantry',
  'semoule': 'pantry',
  'quinoa': 'pantry',
  'farine': 'pantry',
  'sucre': 'pantry',
  'sel': 'pantry',
  'poivre': 'pantry',
  'epice': 'pantry',
  'épice': 'pantry',
  'épices': 'pantry',
  'huile': 'pantry',
  'vinaigre': 'pantry',
  'moutarde': 'pantry',
  'mayonnaise': 'pantry',
  'ketchup': 'pantry',
  'sauce': 'pantry',
  'coulis': 'pantry',
  'concentré de tomate': 'pantry',
  'lentilles': 'pantry',
  'pois chiche': 'pantry',
  'pois chiches': 'pantry',
  'cereales': 'pantry',
  'céréales': 'pantry',
  'biscuit': 'pantry',
  'biscuits': 'pantry',
  'gateau': 'pantry',
  'gâteau': 'pantry',
  'chocolat': 'pantry',
  'confiture': 'pantry',
  'miel': 'pantry',
  'nutella': 'pantry',
  'chips': 'pantry',
  'cacahuetes': 'pantry',
  'noix': 'pantry',
  'bouillon': 'pantry',
  'levure': 'pantry',

  // Boissons
  'eau': 'drinks',
  'evian': 'drinks',
  'cristaline': 'drinks',
  'volvic': 'drinks',
  'perrier': 'drinks',
  'san pellegrino': 'drinks',
  'jus': 'drinks',
  'soda': 'drinks',
  'coca': 'drinks',
  'cola': 'drinks',
  'pepsi': 'drinks',
  'orangina': 'drinks',
  'fanta': 'drinks',
  'ice tea': 'drinks',
  'biere': 'drinks',
  'bière': 'drinks',
  'bieres': 'drinks',
  'vin': 'drinks',
  'cafe': 'drinks',
  'café': 'drinks',
  'the': 'drinks',
  'thé': 'drinks',
  'infusion': 'drinks',
  'sirop': 'drinks',
  'lait d amande': 'drinks',
  'lait d avoine': 'drinks',
  'lait de soja': 'drinks',

  // Surgelés
  'surgele': 'frozen',
  'surgelés': 'frozen',
  'surgelé': 'frozen',
  'glace': 'frozen',
  'glaces': 'frozen',
  'frites': 'frozen',
  'poelee': 'frozen',
  'poêlée': 'frozen',
  'poisson pane': 'frozen',
  'poisson pané': 'frozen',

  // Maison & Hygiène
  'lessive': 'home',
  'adoucissant': 'home',
  'liquide vaisselle': 'home',
  'vaisselle': 'home',
  'eponge': 'home',
  'éponge': 'home',
  'éponges': 'home',
  'sopalin': 'home',
  'essuie-tout': 'home',
  'essuietout': 'home',
  'papier toilette': 'home',
  'pq': 'home',
  'savon': 'home',
  'gel douche': 'home',
  'shampoing': 'home',
  'shampooing': 'home',
  'dentifrice': 'home',
  'brosse a dents': 'home',
  'sac poubelle': 'home',
  'sacs poubelle': 'home',
  'papier alu': 'home',
  'film plastique': 'home',
  'papier cuisson': 'home',
  'pastilles lave-vaisselle': 'home',
  'lave-vaisselle': 'home',
}

// Fonction de détection automatique Bring!
export function detectGroceryCategory(itemName: string): GroceryCategory {
  if (!itemName) return GROCERY_CATEGORIES.find((c) => c.id === 'other')!

  const clean = itemName
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim()

  for (const [kw, catId] of Object.entries(KEYWORDS_TO_CATEGORY)) {
    const cleanKw = kw
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .toLowerCase()
    if (clean === cleanKw || clean.includes(cleanKw) || cleanKw.includes(clean)) {
      const found = GROCERY_CATEGORIES.find((c) => c.id === catId)
      if (found) return found
    }
  }

  return GROCERY_CATEGORIES.find((c) => c.id === 'other')!
}

// Articles populaires Bring! suggérés en 1 clic
export interface BringQuickItem {
  name: string
  emoji: string
  category: string
}

export const BRING_POPULAR_ITEMS: BringQuickItem[] = [
  { name: 'Lait', emoji: '🥛', category: 'dairy' },
  { name: 'Pain', emoji: '🍞', category: 'bakery' },
  { name: 'Œufs', emoji: '🥚', category: 'dairy' },
  { name: 'Bananes', emoji: '🍌', category: 'produce' },
  { name: 'Pâtes', emoji: '🍝', category: 'pantry' },
  { name: 'Beurre', emoji: '🧈', category: 'dairy' },
  { name: 'Tomates', emoji: '🍅', category: 'produce' },
  { name: 'Fromage râpé', emoji: '🧀', category: 'dairy' },
  { name: 'Café', emoji: '☕', category: 'drinks' },
  { name: 'Poulet', emoji: '🍗', category: 'meat' },
  { name: 'Riz', emoji: '🍚', category: 'pantry' },
  { name: 'Huile d’olive', emoji: '🫒', category: 'pantry' },
  { name: 'Sopalin', emoji: '🧻', category: 'home' },
  { name: 'Eau', emoji: '💧', category: 'drinks' },
]
